name: Vigilia de Chronos

on:
  schedule:
    # 11:00 UTC = 08:00 Brasília (Foco: Exercícios)
    # 00:00 UTC = 21:00 Brasília (Foco: Finanças)
    - cron: '0 11,0 * * *'
  workflow_dispatch: # Botão para rodar manualmente

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código
        uses: actions/checkout@v3

      - name: Preparar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar Dependências
        run: npm install

      - name: Executar Golem
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: node golem.js

        # --- PARTE DO ORÁCULO (PYTHON) ---
      - name: Preparar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Atualizei para 3.11 para evitar o aviso de suporte que apareceu no seu log

      - name: Instalar Dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin requests beautifulsoup4 google-genai python-dotenv

      - name: Executar Oráculo (Monitor de Editais)
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}      # ADICIONE ISSO
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}  # ADICIONE ISSO
        run: python oraculo.py